steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_IMAGE_NAME}:$SHORT_SHA",
        "--build-arg", "JAR_FILE=target/*.jar",
        "."
      ]

  # Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_IMAGE_NAME}:$SHORT_SHA",
      ]

  # Deploy to GKE cluster
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - "run"
      - "--filename=kubernetes"
      - "--image=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_IMAGE_NAME}:$SHORT_SHA"
      - "--location=${_LOCATION}"
      - "--cluster=${_GKE_CLUSTER_NAME}"
      - "--verbose"

# Store the built images in Artifact Registry
images:
  - "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY_NAME}/${_IMAGE_NAME}:$SHORT_SHA"
